name: Release macOS

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package binary
        run: |
          mkdir -p dist
          cp build/fm_drum_synth dist/

      - name: Bundle runtime dependencies
        run: |
          mkdir -p dist
          cp build/fm_drum_synth dist/
          cp build/_deps/rtaudio-build/librtaudio.8.dylib dist/
          cp build/_deps/glfw-build/src/libglfw.3.3.dylib dist/

      - name: Zip release
        run: |
          cd dist
          zip -r fm_drum_synth-macOS.zip fm_drum_synth librtaudio.8.dylib libglfw.3.3.dylib

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/fm_drum_synth-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
